version: 0.2.{build}
image: Visual Studio 2017
configuration: Release
cache:
  - Source\packages -> **\Source\repositories.config
before_build:
  - cmd: appveyor_prebuild.cmd
build:
  project: Source
  parallel: true
  verbosity: minimal