version: 0.2.{build}
image: Visual Studio 2015
configuration: Release
cache: Source\packages -> **\Source\repositories.config
before_build:
- cmd: nuget restore Source\nGratis.Cop.Theia.sln
build:
  project: Source
  parallel: true
  verbosity: minimal