//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nGratis.Cop.Core.Contract.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("nGratis.Cop.Core.Contract.Localization.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting property [{0}] on frozen instance with type [{1}] is not allowed..
        /// </summary>
        internal static string FreezableAspect_Exception_FrozenInstanceManipulation {
            get {
                return ResourceManager.GetString("FreezableAspect_Exception_FrozenInstanceManipulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current instance with type [{0}] is not inheriting interface [{1}]..
        /// </summary>
        internal static string FreezableAspect_Exception_NonFreezableInstance {
            get {
                return ResourceManager.GetString("FreezableAspect_Exception_NonFreezableInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter [{0}] cannot be &lt;default&gt;..
        /// </summary>
        internal static string Guard_Exception_DefaultArgument {
            get {
                return ResourceManager.GetString("Guard_Exception_DefaultArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter [{0}] is not valid..
        /// </summary>
        internal static string Guard_Exception_InvalidArgument {
            get {
                return ResourceManager.GetString("Guard_Exception_InvalidArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation is not valid..
        /// </summary>
        internal static string Guard_Exception_InvalidOperation {
            get {
                return ResourceManager.GetString("Guard_Exception_InvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter [{0}] cannot be &lt;null&gt;..
        /// </summary>
        internal static string Guard_Exception_NullArgument {
            get {
                return ResourceManager.GetString("Guard_Exception_NullArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter [{0}] cannot be &lt;null&gt; or contains only whitespaces..
        /// </summary>
        internal static string Guard_Exception_StringNullOrWhitespace {
            get {
                return ResourceManager.GetString("Guard_Exception_StringNullOrWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable value is not expected to be &lt;null&gt;..
        /// </summary>
        internal static string Guard_Exception_UnexpectedNullValue {
            get {
                return ResourceManager.GetString("Guard_Exception_UnexpectedNullValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason: {0}..
        /// </summary>
        internal static string Guard_Label_Reason {
            get {
                return ResourceManager.GetString("Guard_Label_Reason", resourceCulture);
            }
        }
    }
}
